#+TITLE: Medidas de la desigualdad de la renta --- Soluciones
#+SETUPFILE: ../setup.org


#+begin_tcolorbox
#+ATTR_LATEX: :options [1., series = questions]
1. En la hoja =Rentas= del archivo Excel =ineq-data.xlsx= se presentan
   las rentas anuales en euros de los 10 habitantes de un país
   hipotético.

   #+ATTR_LATEX: :options [(a)]
   a) Obtenga y represente gráficamente la curva de Lorenz.
#+end_tcolorbox

#+begin_tcolorbox
   #+ATTR_LATEX: :options [(a), series = inner, start = 2, leftmargin=1.8cm]
   b) Calcule el índice de Gini y el cociente /S80S20/.
#+end_tcolorbox

#+begin_tcolorbox
   #+ATTR_LATEX: :options [resume* = inner]
   c) Calcule el índice de Gini y el cociente /S80S20/ cuando se
      transfieren \money{2 000} del individuo 1 al individuo 3. ¿Cómo
      cambian los indicadores de desigualdad?
#+end_tcolorbox

#+begin_tcolorbox
   #+ATTR_LATEX: :options [resume* = inner]
   d) Calcule el índice de Gini y el cociente /S80S20/ si se
      transfieren \money{2 000} del individuo 8 al individuo 10. ¿Cómo
      cambian ahora los indicadores de desigualdad?
#+end_tcolorbox

#+begin_tcolorbox
   #+ATTR_LATEX: :options [resume* = inner]
   e) Compare las respuestas obtenidas en los dos apartados
      anteriores. ¿Cuál de los índices de desigualdad es más adecuado
      en este caso?
#+end_tcolorbox

#+begin_tcolorbox
#+ATTR_LATEX: :options [resume* = questions]
2. En la hoja =CC.AA.= del archivo Excel =ineq-data.xlsx= se presentan
   datos de las Comunidades Autónomas españolas correspondientes a los
   años 2013 y 2023 y que muestran como ha evolucionado el crecimiento
   económico, la desigualdad de la renta y la pobreza en las distintas
   Comunidades. En su respuesta no incluya los casos de las Ciudades
   Autónomas de Ceuta y Melilla dado que presentan características muy
   diferentes al resto de España. También tenga en cuenta que las
   rentas medias no están ajustadas al incremento de los precios
   durante ese periodo. Para comparar las rentas medias en años
   diferentes es conveniente deflactarlas previamente con el
   IPC. Utilizando los datos proporcionados compruebe si existe alguna
   relación entre el crecimiento económico y la pobreza. ¿Disminuye
   más la pobreza en las Comunidades que crecen más? ¿Están
   relacionados el crecimiento y la desigualdad? ¿De qué forma? ¿Y la
   desigualdad y la pobreza?
#+end_tcolorbox

[[file:../figures/Gini.pdf]]

[[file:../figures/S80S20.pdf]]

file:../figures/H.pdf

file:../figures/ypc.pdf


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:
